# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    # ID of the build.
    # Defaults to the project name.
    id: "wallertme"

    # Path to project's (sub)directory containing Go code.
    # This is the working directory for the Go build command(s).
    # Default is `.`.
    # dir: go

    # Path to main.go file or main package.
    # Notice: when used with `gomod.proxy`, this must be a package.
    #
    # Default is `.`.
    main: ./cmd/cli

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: wallertmectl

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/piqba/wallertme/cmd/cli/commands.Version={{.Version}} -X github.com/piqba/wallertme/cmd/cli/commands.VersionHash={{.Commit}} -X github.com/piqba/wallertme/cmd/cli/commands.BuildTime={{.Date}}
      - -s -w -X github.com/piqba/wallertme/cmd/cli/commands.OtelNameBb8="bb8" -X github.com/piqba/wallertme/cmd/cli/commands.OtelNameR2D2="r2d2" -X github.com/piqba/wallertme/cmd/cli/commands.OtelVersion={{.Version}} -X main.OtelNameEnv="dev"


    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - docs/*
      - README.md
      - wallets_template.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
